site_name: Cocos Documentation
site_url: http://cocos2d-x.org/documentation
site_description: Cocos Documentation.
site_author: The Cocos Teams
pages:
- Home: 'index.md'
- Contents:
    - 'Cocos': 'cocos/cocos.md'
    - 'Manual Installations':
        - 'Prerequisites': 'installation/A.md'
        - 'Android (Terminal) Setup': 'installation/B.md'
        - 'Android (Eclipse) Setup': 'installation/C.md'
        - 'IOS Setup': 'installation/D.md'
        - 'Mac OSX Setup': 'installation/E.md'
        - 'Linux Setup': 'installation/F.md'
        - 'Windows Setup': 'installation/G.md'
        - 'Windows Phone Setup': 'installation/H.md'
    - 'Programmers Guide':
        - 'About Cocos2d-x': 'programmers-guide/1.md'
        - 'Basic Concepts': 'programmers-guide/2.md'
        - 'Sprites': 'programmers-guide/3.md'
        - 'Actions': 'programmers-guide/4.md'
        - 'Scenes': 'programmers-guide/5.md'
        - 'UI': 'programmers-guide/6.md'
        - 'Other Node Types': 'programmers-guide/7.md'
        - 'Event Dispatch': 'programmers-guide/8.md'
        - '3D': 'programmers-guide/9.md'
        - 'Scripting': 'programmers-guide/10.md'
        - 'Physics': 'programmers-guide/11.md'
        - 'Audio': 'programmers-guide/12.md'
        - 'Advanced Topics': 'programmers-guide/13.md'
    - 'Editors & Tools':
        - 'Cocos command-line tool': 'editors_and_tools/cocosCLTool.md'
        - 'Studio': 'editors_and_tools/studio.md'
        - '_Workspace_Overview': 'editors_and_tools/Workspace_Overview/en.md'
        - '_CodeAndDebug': 'editors_and_tools/chapter2/CodeAndDebug/en.md'
        - '_PackageAndRun': 'editors_and_tools/chapter2/PackageAndRun/en.md'
        - '_Publish': 'editors_and_tools/chapter2/Publish/en.md'
        - '_SceneAndLayer': 'editors_and_tools/chapter2/SceneAndLayer/en.md'
        - '_SpriteSheet': 'editors_and_tools/chapter2/SpriteSheet/en.md'
        - '_Basic Objects': 'editors_and_tools/chapter3/UI/BasicObjects/en.md'
        - '_Widgets': 'editors_and_tools/chapter3/UI/Widgets/en.md'
        - '_Containers': 'editors_and_tools/chapter3/UI/Containers/en.md'
        - '_Armature': 'editors_and_tools/chapter3/UI/Armature/en.md'
        - '_UI Layout and Multi-resolution Support': 'editors_and_tools/chapter3/UI/Layout/en.md'
        - '_9-Slice': 'editors_and_tools/chapter3/UI/9Slice/en.md'
        - '_Rulers and Guides': 'editors_and_tools/chapter3/UI/RulersGuides/en.md'
        - '_Create 2D SpriteSheet Animation': 'editors_and_tools/chapter3/Animation/2DSpriteSheetAnimation/en.md'
        - '_Key Frames': 'editors_and_tools/chapter3/Animation/InsertKeyframe/en.md'
        - '_Create a Frame Event': 'editors_and_tools/chapter3/Animation/AddFrameEvents/en.md'
        - '_Create a Skeletal Animation': 'editors_and_tools/chapter3/Animation/CreateSkeletalAnimation/en.md'
        - '_Edit Skeletal Animation': 'editors_and_tools/chapter3/Animation/EditSkeletalAnimation/en.md'
        - '_How to -> Create a Skeletal Animation with cocos': 'editors_and_tools/chapter3/Animation/Sample/en.md'
        - '_Use Skeletal Animation': 'editors_and_tools/chapter3/Animation/UseSkeletalAnimation/en.md'
        - '_Create 3D Scenes': 'editors_and_tools/chapter3/3D/New3DScene/en.md'
        - '_3D Model Overview': 'editors_and_tools/chapter3/3D/3DModel/en.md'
        - '_3D Particles Overview': 'editors_and_tools/chapter3/3D/3DParticle/en.md'
        - '_Camera': 'editors_and_tools/chapter3/3D/Camera/en.md'
        - '_3D Keyboard Shortcuts': 'editors_and_tools/chapter3/3D/3DShortcutKey/en.md'
        - '_3D Node Overview': 'editors_and_tools/chapter3/3D/3DNode/en.md'
        - '_SkyBox': 'editors_and_tools/chapter3/3D/SkyBox/en.md'
        - '_Light': 'editors_and_tools/chapter3/3D/Light/en.md'
        - '_Widgets Extension': 'editors_and_tools/chapter3/Extend/WidgetExtend/en.md'
        - '_Properties Extension': 'editors_and_tools/chapter3/Extend/ParamExtend/en.md'
        - '_Customizing Exported Data Formats': 'editors_and_tools/chapter3/Extend/CustomExport/en.md'
        - '_Samples': 'editors_and_tools/chapter3/Extend/Sample/en.md'
        - '_Callback Feature': 'editors_and_tools/chapter3/HowToCode/CallBack/en.md'
        - '_Create Custom Data': 'editors_and_tools/chapter3/HowToCode/UserData/en.md'
        - '_Load Exported Data': 'editors_and_tools/chapter3/HowToCode/LoadExportData/en.md'
        - '_Customize Cocos Framework & Simulator': 'editors_and_tools/chapter3/HowToCode/CustomizeFramework-v3.10/en.md'
        - '_1 No Android Devices Found': 'editors_and_tools/chapter4/connect-solution/en.md'
        - '_2 How to -> Debug Browser Preview': 'editors_and_tools/chapter4/debug-on-browser/en.md'
        - '_3 How to -> Use CCLog to Debug project based on precompiled library': 'editors_and_tools/chapter4/FWNoLog/en.md'
        - '_4 How to -> Use FBX File': 'editors_and_tools/chapter4/HowToUseFBX/en.md'
        - '_5 How to -> Load SpriteSheet Correctly': 'editors_and_tools/chapter4/OnePixelBug/en.md'
        - '_6 How to -> Preload Resources': 'editors_and_tools/chapter4/PreloadRes/en.md'
        - '_7 How to -> Automatically Wrap Text and Adjust Height of Text': 'editors_and_tools/chapter4/TextAuto/en.md'
        - '_8 Two Automatic Recursive Function on UIHelper': 'editors_and_tools/chapter4/UIHelperGetNode/en.md'
        - '_9 Issues about Upgrading or Downgrading Framework': 'editors_and_tools/chapter4/upgrade-framework/en.md'
        - '_10 How to -> Load Data Exported from cocos': 'editors_and_tools/chapter4/LoadError/en.md'
        - '_11 How to -> Import Project from v1.6': 'editors_and_tools/chapter4/Import1.6ProjectError/en.md'
        - '_12 Customize Framework(v3.7)': 'editors_and_tools/chapter3/HowToCode/CustomizeFramework/en.md'
        - '_13 Customize Framework(v3.8~3.9)': 'editors_and_tools/chapter3/HowToCode/CustomizeFramework-v3.8/en.md'
        - '_14 Customize precompiled library(v3.10)': 'editors_and_tools/chapter3/HowToCode/CustomizeFramework-v3.10/en.md'
        - '_15 How to -> Fix Packaging and Running Issues': 'editors_and_tools/chapter4/FixPackageError/en.md'
        - '_16 How to -> Simplify Widgets Initial Resources': 'editors_and_tools/chapter4/SimplifyWidgetsRes/en.md'
        - '_17 How to -> Run Previous Versions of Addins in cocos': 'editors_and_tools/chapter4/PluginLoadError/en.md'
        - '_18 How to -> Fix cocos Run Error?': 'editors_and_tools/chapter4/runError/en.md'
    - 'Services':
        - 'SDKBOX': 'services/sdkbox.md'
    - 'Tutorials':
        - 'JavaScript': 'tutorials/javascript/javascript.md'
        - '_Chapter2': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter2/en.md'
        - '_Chapter3': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter3/en.md'
        - '_Chapter4': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter4/en.md'
        - '_Chapter5': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter5/en.md'
        - '_Chapter6': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter6/en.md'
        - '_Chapter7': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter7/en.md'
        - '_Chapter8': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter8/en.md'
        - '_Chapter9': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter9/en.md'
        - '_Chapter10': 'tutorials/javascript/parkour-game-with-javascript-v3.0/chapter10/en.md'
    - 'API Reference': 'api-ref/index.md'
#- About: 'title.md'

#theme: readable
theme_dir: 'theme'
copyright: Copyright (c) 2014-2016 Chukong Technologies Inc.
use_directory_urls: false
repo_url: https://github.com/chukong/cocos-docs
repo_name: GitHub
google_analytics: ['UA-3216502-3', 'Cocos2d-x.org']
