site_name: Cocos Documentation
site_url: http://cocos2d-x.org/documentation
site_description: Cocos Documentation.
site_author: The Cocos Teams
pages:
- Home: 'index.md'
- Contents:
    - 'Cocos': 'cocos/cocos.md'
    - 'Manual Installations':
        - 'Prerequisites': 'installation/A.md'
        - 'Android (Terminal) Setup': 'installation/B.md'
        - 'Android (Eclipse) Setup': 'installation/C.md'
        - 'IOS Setup': 'installation/D.md'
        - 'Mac OSX Setup': 'installation/E.md'
        - 'Linux Setup': 'installation/F.md'
        - 'Windows Setup': 'installation/G.md'
        - 'Windows Phone Setup': 'installation/H.md'
        - 'Command-line Integration': 'installation/I.md'
    - 'Programmers Guide':
        - 'About Cocos2d-x': 'programmers-guide/1.md'
        - 'Basic Concepts': 'programmers-guide/2.md'
        - 'Sprites': 'programmers-guide/3.md'
        - 'Actions': 'programmers-guide/4.md'
        - 'Scenes': 'programmers-guide/5.md'
        - 'UI': 'programmers-guide/6.md'
        - 'Other Node Types': 'programmers-guide/7.md'
        - 'Event Dispatch': 'programmers-guide/8.md'
        - '3D': 'programmers-guide/9.md'
        - 'Scripting': 'programmers-guide/10.md'
        - 'Physics': 'programmers-guide/11.md'
        - 'Audio': 'programmers-guide/12.md'
        - 'Advanced Topics': 'programmers-guide/13.md'
    - 'Services':
      - 'SDKBOX': 'services/sdkbox.md'
    - 'API Reference': 'api-ref/index.md'
#- About: 'title.md'

#theme: readable
theme_dir: 'theme'
copyright: Copyright (c) 2014-2016 Chukong Technologies Inc.
use_directory_urls: false
repo_url: https://github.com/chukong/cocos-docs
repo_name: GitHub
google_analytics: ['UA-3216502-3', 'Cocos2d-x.org']
